name_="张三"
_name="张三"
name_t="黑马程序员"
name='万花筒写轮眼'
name1="宇智波佐助"
name2="""宇智波斑"""
print("学IT就来%s"%name_t)
print("宇智波斑拥有%s"%name)
print("宇智波斑和宇智波佐助拥有%s"%name)
print(name1+name2+name)
print(type(name))
print(type(name1))
print(type(name2))
print(name)
print(name1)
print(name2)
print(name_)
print(_name)
print(name_t)
print("1+1=",1+1)
print("1000*5=",1000*5)
num=1
print(num)
num+=1
print(num)
num*=2
print(num)
class_num=57
ave_salary=16780
message="北京程序员的最大年龄为%s,平均薪资为%s"%(class_num,ave_salary)
print(message)
print(f"1*8的结果是：%d"%(1*8))
print(f"2*8的结果是：{2*8}")
